### ISSUE TITLE
.rpm Package does not open

### ISSUE THREAD

**Issue by universish** [szTheory/exifcleaner#254]
The exifcleaner-3.6.0.x86_64.rpm file can be installed. But it does not open. My operating system is fedora 40. My desktop environment is gnome wayland.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by universish** [comment]
wayland?

**Comment by universish** [comment]
macellan@fedora:~/İndirilenler/çıktı_klasörü$ rpm -qa | grep exifcleaner
exifcleaner-3.6.0-1.x86_64
macellan@fedora:~/İndirilenler/çıktı_klasörü$ which exifcleaner
/usr/bin/exifcleaner
macellan@fedora:~/İndirilenler/çıktı_klasörü$ rpm -qi exifcleaner
Name        : exifcleaner
Version     : 3.6.0
Release     : 1
Architecture: x86_64
Install Date: Pzt 28 Eki 2024 01:13:58
Group       : default
Size        : 208328776
License     : MIT
Signature   : (none)
Source RPM  : exifcleaner-3.6.0-1.src.rpm
Build Date  : Sal 04 May 2021 15:12:17
Build Host  : jons-mac-mini-2.local
Relocations : / 
Packager    : szTheory <szTheory@users.noreply.github.com>
Vendor      : szTheory <szTheory@users.noreply.github.com>
URL         : https://github.com/szTheory/exifcleaner#readme
Summary     : Clean exif metadata from images, videos, and PDF documents
Description :
Clean exif metadata from images, videos, and PDF documents
macellan@fedora:~/İndirilenler/çıktı_klasörü$ exifcleaner
internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at Object.resolve (path.js:978:47)
    at resolveMainPath (internal/modules/run_main.js:12:40)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:65:24)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
macellan@fedora:~/İndirilenler/çıktı_klasörü$ uname -a
Linux fedora 6.11.4-201.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 20 15:04:22 UTC 2024 x86_64 GNU/Linux
macellan@fedora:~/İndirilenler/çıktı_klasörü$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
macellan@fedora:~/İndirilenler/çıktı_klasörü$ lsb_release -a
shell-init: geçerli dizin alınırken hata: getcwd: üst dizinlere erişilemiyor: Böyle bir dosya ya da dizin yok
LSB Version:	:core-5.0-amd64:core-5.0-noarch
Distributor ID:	Fedora
Description:	Fedora release 40 (Forty)
Release:	40
Codename:	Forty
macellan@fedora:~/İndirilenler/çıktı_klasörü$ echo $DISPLAY
:0
macellan@fedora:~/İndirilenler/çıktı_klasörü$ loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
Type=wayland
macellan@fedora:~/İndirilenler/çıktı_klasörü$ ps -e | grep -E 'Xwayland|Xorg'
  14242 ?        00:00:00 Xwayland
macellan@fedora:~/İndirilenler/çıktı_klasörü$ echo $XDG_SESSION_TYPE
wayland
macellan@fedora:~/İndirilenler/çıktı_klasörü$ echo $XDG_CURRENT_DESKTOP
GNOME
macellan@fedora:~/İndirilenler/çıktı_klasörü$ echo $DESKTOP_SESSION
gnome

**Comment by universish** [comment]
```
macellan@fedora:~$ rpm -qa | grep exifcleaner
exifcleaner-3.6.0-1.x86_64
```
```
macellan@fedora:~$ which exifcleaner
/usr/bin/exifcleaner
```
```
macellan@fedora:~$ rpm -qi exifcleaner
Name        : exifcleaner
Version     : 3.6.0
Release     : 1
Architecture: x86_64
Install Date: Pzt 28 Eki 2024 01:13:58
Group       : default
Size        : 208328776
License     : MIT
Signature   : (none)
Source RPM  : exifcleaner-3.6.0-1.src.rpm
Build Date  : Sal 04 May 2021 15:12:17
Build Host  : jons-mac-mini-2.local
Relocations : / 
Packager    : szTheory <szTheory@users.noreply.github.com>
Vendor      : szTheory <szTheory@users.noreply.github.com>
URL         : https://github.com/szTheory/exifcleaner#readme
Summary     : Clean exif metadata from images, videos, and PDF documents
Description :
Clean exif metadata from images, videos, and PDF documents
```
```
macellan@fedora:~$ exifcleaner
internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at Object.resolve (path.js:978:47)
    at resolveMainPath (internal/modules/run_main.js:12:40)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:65:24)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

```
macellan@fedora:~$ uname -a
Linux fedora 6.11.4-201.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 20 15:04:22 UTC 2024 x86_64 GNU/Linux
```

```
macellan@fedora:~$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

```
macellan@fedora:~$ lsb_release -a
shell-init: geçerli dizin alınırken hata: getcwd: üst dizinlere erişilemiyor: Böyle bir dosya ya da dizin yok
LSB Version:	:core-5.0-amd64:core-5.0-noarch
Distributor ID:	Fedora
Description:	Fedora release 40 (Forty)
Release:	40
Codename:	Forty
```

```
macellan@fedora:~$ echo $DISPLAY
:0
```
```
macellan@fedora:~$ loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
Type=wayland
```
```
macellan@fedora:~$ ps -e | grep -E 'Xwayland|Xorg'
  14242 ?        00:00:00 Xwayland
```
```
macellan@fedora:~$ echo $XDG_SESSION_TYPE
wayland
```
```
macellan@fedora:~$ echo $XDG_CURRENT_DESKTOP
GNOME
```
```
macellan@fedora:~$ echo $DESKTOP_SESSION
gnome
```

**Comment by universish** [comment]
```
macellan@fedora:~$ exifcleaner
(node:19982) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[19982:1028/013921.477763:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
İzleme/kesme noktası yakalayıcı (çekirdek döküldü)

```

translated:
```
macellan@fedora:~$ exifcleaner
(node:19982) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[19982:1028/013921.477763:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint catcher (kernel spilled)
```

**Comment by universish** [comment]
```
macellan@fedora:~$ rpm -qa | grep exifcleaner
exifcleaner-3.6.0-1.x86_64
```
```
macellan@fedora:~$ which exifcleaner
/usr/bin/exifcleaner
```
```
macellan@fedora:~$ rpm -qi exifcleaner
Name        : exifcleaner
Version     : 3.6.0
Release     : 1
Architecture: x86_64
Install Date: Pzt 28 Eki 2024 01:13:58
Group       : default
Size        : 208328776
License     : MIT
Signature   : (none)
Source RPM  : exifcleaner-3.6.0-1.src.rpm
Build Date  : Sal 04 May 2021 15:12:17
Build Host  : jons-mac-mini-2.local
Relocations : / 
Packager    : szTheory <szTheory@users.noreply.github.com>
Vendor      : szTheory <szTheory@users.noreply.github.com>
URL         : https://github.com/szTheory/exifcleaner#readme
Summary     : Clean exif metadata from images, videos, and PDF documents
Description :
Clean exif metadata from images, videos, and PDF documents
```

```
macellan@fedora:~$ uname -a
Linux fedora 6.11.4-201.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 20 15:04:22 UTC 2024 x86_64 GNU/Linux
```

```
macellan@fedora:~$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

```
macellan@fedora:~$ lsb_release -a
shell-init: geçerli dizin alınırken hata: getcwd: üst dizinlere erişilemiyor: Böyle bir dosya ya da dizin yok
LSB Version:	:core-5.0-amd64:core-5.0-noarch
Distributor ID:	Fedora
Description:	Fedora release 40 (Forty)
Release:	40
Codename:	Forty
```

```
macellan@fedora:~$ echo $DISPLAY
:0
```
```
macellan@fedora:~$ loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
Type=wayland
```
```
macellan@fedora:~$ ps -e | grep -E 'Xwayland|Xorg'
  14242 ?        00:00:00 Xwayland
```
```
macellan@fedora:~$ echo $XDG_SESSION_TYPE
wayland
```
```
macellan@fedora:~$ echo $XDG_CURRENT_DESKTOP
GNOME
```
```
macellan@fedora:~$ echo $DESKTOP_SESSION
gnome
```

**Comment by universish** [comment]
I don't know how to do it. How can I find out the dependencies? 
There is nothing in the README file about the dependencies that need to be installed.

**Comment by luisegarduno** [comment]
> ```
> macellan@fedora:~$ exifcleaner
> (node:19982) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> [19982:1028/013921.477763:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
> İzleme/kesme noktası yakalayıcı (çekirdek döküldü)
> ```
> 
> translated:
> 
> ```
> macellan@fedora:~$ exifcleaner
> (node:19982) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> [19982:1028/013921.477763:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
> Trace/breakpoint catcher (kernel spilled)
> ```

<br/>

What happens when you run `exifcleaner --disable-gpu-sandbox` (https://github.com/szTheory/exifcleaner/issues/238#issuecomment-1668369931)?
^ If this works, you can make things easier by creating a new alias to overwrite the original one:
```bash
#  add this to your ~/.bashrc
alias exifcleaner='exifcleaner --disable-gpu-sandbox'
```

If adding `--disable-gpu-sandbox` doesn't work, you can also try `sudo exifcleaner --no-sandbox`

**Comment by HongPong** [comment]
also having this issue thank you. happily does launch with `./ExifCleaner-3.6.0.AppImage --disable-gpu-sandbox` , the AppImage version.

**Comment by universish** [comment]
> What happens when you run
I deleted fedora. I switched to windows.

**Comment by szTheory** [comment]
Worth a retest on **v4.0.0** — https://github.com/szTheory/exifcleaner/releases

Two things changed that bear on this: the app moved to Electron 35, and the Linux packages are now built and smoke-tested in CI on every release — the AppImage is actually installed and launched, not just produced.

I don't have a Fedora machine, so I can't confirm from here. If it still fails, please say which package (AppImage / deb / rpm) and paste any terminal output.

**Comment by szTheory** [comment]
ExifCleaner 4.0.1 is now available: https://github.com/szTheory/exifcleaner/releases/tag/v4.0.1

Please retest the RPM on Fedora with GNOME Wayland using this exact version. If there is no update by **2026-09-01**, this issue will be closed as stale; a later reproduction can still be reported.

**Comment by IkelAtomig** [comment]
Fedora 44 Workstation user here. I can confirm that Exifcleaner works as intended and operations are smoother without a hiccup.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by szTheory** [comment]
Closing as confirmed fixed. Current RPM artifacts are installed and launched in native release smoke, and a Fedora 44 Workstation user confirmed the current app works as intended.
