### ISSUE TITLE
Occassional "Error: Exiftool process is not open" when processing files and have to retry it

### ISSUE THREAD

**Issue by zahroc** [szTheory/exifcleaner#83]
When adding 132 directories with 2 files per directory, I got the following error twice before it started processing:

Unhandled Promise Rejection
Error: Exiftool process is not open
    at ExiftoolProcess.close (C:/Users/sysadmin/AppData/Local/Programs/exifcleaner/resources/app.asar/node_modules/node-exiftool/src/index.js:33:35)
    at exifData (file:///C:/Users/sysadmin/AppData/Local/Programs/exifcleaner/resources/app.asar/webpack:/src/renderer/add_files.ts:39:6)
    at showExifBeforeClean (file:///C:/Users/sysadmin/AppData/Local/Programs/exifcleaner/resources/app.asar/webpack:/src/renderer/add_files.ts:43:44)

It seems to be running but what is the issue and which did it error on?

**Comment by szTheory** [comment]
Sorry about that. ExifCleaner doesn't currently support adding directories. It gets confused when you try to add one. At the moment you have to go into a directory then select the files you want to clean, and drag them in.

I think this is a bug and should be fixed though. So I'll add it to the development queue.

**Comment by zahroc** [comment]
Thanks!
It does work most of the time when drag n drop folders 8-)

**Comment by szTheory** [comment]
Oh you know what, this might be fixed by this next release I'm working on. It reuses the same open `exiftool` process for each operation. It's way faster and more stable. I'll circle back and let you know when it's ready. Still doing cross platform testing.

**Comment by szTheory** [comment]
@zahroc I was able to reproduce this when I was testing in Windows. Not sure what the problem is. Almost like it tries to use the `exiftool` process before it's done spinning up. I've just released a new version that uses a more efficient algorithm if you want to give it a try and see if it helps https://github.com/szTheory/exifcleaner/releases/tag/v3.4.0

**Comment by zahroc** [comment]
I will give it a shot and let you know the results. Thanks!
